import { useEffect, useMemo, useState } from "react";
import api from "../../api";
import { StatusBadge } from "./Dashboard";

const statusFilters = [{ value: "", label: "Tất cả" }, { value: "pending", label: "Chờ xác nhận" }, { value: "confirmed", label: "Đã xác nhận" }, { value: "cancelled", label: "Đã hủy" }];
const dateLabel = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString("vi-VN", { day: "2-digit", month: "short", year: "numeric" }) : "—";

export default function BookingsManager() {
  const [bookings, setBookings] = useState([]); const [filter, setFilter] = useState(""); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true);
  function load() { setLoading(true); api.get("/bookings", { params: filter ? { status: filter } : {} }).then((res) => setBookings(res.data)).finally(() => setLoading(false)); }
  useEffect(load, [filter]);
  const visible = useMemo(() => { const keyword = query.trim().toLocaleLowerCase(); return keyword ? bookings.filter((b) => [b.customerName, b.phone, b.email, b.roomName].some((item) => String(item || "").toLocaleLowerCase().includes(keyword))) : bookings; }, [bookings, query]);
  const counts = useMemo(() => ({ all: bookings.length, pending: bookings.filter((b) => b.status === "pending").length, confirmed: bookings.filter((b) => b.status === "confirmed").length }), [bookings]);
  async function updateStatus(id, status) { await api.put(`/bookings/${id}/status`, { status }); load(); }
  async function removeBooking(id) { if (confirm("Xóa đơn đặt phòng này? Hành động không thể hoàn tác.")) { await api.delete(`/bookings/${id}`); load(); } }
  const Actions = ({ booking }) => <div className="flex gap-1.5 justify-end flex-wrap">{booking.status !== "confirmed" && <button onClick={() => updateStatus(booking.id, "confirmed")} className="admin-action admin-confirm">Xác nhận</button>}{booking.status !== "cancelled" && <button onClick={() => updateStatus(booking.id, "cancelled")} className="admin-action admin-cancel">Hủy</button>}<button onClick={() => removeBooking(booking.id)} className="admin-action admin-delete" aria-label="Xóa đơn">×</button></div>;
  return <div>
    <div className="flex flex-col xl:flex-row xl:items-end justify-between gap-5 mb-7"><div><p className="admin-eyebrow">VẬN HÀNH · ĐẶT PHÒNG</p><h1 className="text-2xl sm:text-3xl font-bold text-slate-800 mt-1">Đơn đặt phòng</h1><p className="text-sm text-slate-500 mt-1">Theo dõi và phản hồi khách hàng kịp thời.</p></div><div className="admin-booking-stats"><span><b>{counts.all}</b> tổng đơn</span><span><b>{counts.pending}</b> chờ xử lý</span><span><b>{counts.confirmed}</b> đã xác nhận</span></div></div>
    <div className="card p-3 sm:p-4 mb-5 flex flex-col md:flex-row gap-3 md:items-center"><label className="admin-search"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm tên khách, số điện thoại, phòng..." /></label><div className="flex gap-2 flex-wrap">{statusFilters.map((item) => <button key={item.value} onClick={() => setFilter(item.value)} className={`admin-filter ${filter === item.value ? "admin-filter-active" : ""}`}>{item.label}</button>)}</div></div>
    {loading && <div className="card p-8 text-center text-sm text-slate-400">Đang tải danh sách đơn đặt phòng…</div>}
    {!loading && !visible.length && <div className="card p-10 text-center"><p className="text-3xl mb-3">🗓️</p><p className="font-semibold text-slate-700">Chưa có đơn phù hợp</p><p className="text-sm text-slate-400 mt-1">Thử thay đổi bộ lọc hoặc từ khóa tìm kiếm.</p></div>}
    {!loading && visible.length > 0 && <div className="hidden md:block card overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-500 text-left"><tr><th className="px-5 py-4 font-semibold">Khách hàng</th><th className="px-4 py-4 font-semibold">Phòng</th><th className="px-4 py-4 font-semibold">Lưu trú</th><th className="px-4 py-4 font-semibold">Khách</th><th className="px-4 py-4 font-semibold">Trạng thái</th><th className="px-5 py-4 font-semibold text-right">Thao tác</th></tr></thead><tbody>{visible.map((booking) => <tr key={booking.id} className="border-t border-slate-100 hover:bg-slate-50/70 transition-colors"><td className="px-5 py-4"><p className="font-semibold text-slate-700">{booking.customerName}</p>{booking.bookingCode && <p className="text-[10px] tracking-wider font-bold text-brand mt-1">{booking.bookingCode}</p>}<p className="text-xs text-slate-400 mt-1">{booking.phone}{booking.email ? ` · ${booking.email}` : ""}</p>{booking.note && <p className="text-xs text-slate-400 italic mt-1 max-w-xs truncate">“{booking.note}”</p>}</td><td className="px-4 py-4 font-medium text-slate-600">{booking.roomName}</td><td className="px-4 py-4 whitespace-nowrap text-slate-600"><b className="font-medium">{dateLabel(booking.checkIn)}</b><span className="block text-xs text-slate-400 mt-1">đến {dateLabel(booking.checkOut)}</span></td><td className="px-4 py-4 text-slate-600">{booking.adults} NL{booking.children ? ` · ${booking.children} TE` : ""}</td><td className="px-4 py-4"><StatusBadge status={booking.status} /></td><td className="px-5 py-4"><Actions booking={booking} /></td></tr>)}</tbody></table></div>}
    {!loading && visible.length > 0 && <div className="md:hidden space-y-3">{visible.map((booking) => <article key={booking.id} className="card p-4"><div className="flex justify-between gap-3"><div><h2 className="font-semibold text-slate-800">{booking.customerName}</h2><p className="text-xs text-slate-400 mt-1">{booking.phone}</p></div><StatusBadge status={booking.status} /></div><div className="grid grid-cols-2 gap-3 text-sm mt-4 py-3 border-y border-slate-100"><p className="text-slate-500"><span className="block text-xs text-slate-400">PHÒNG</span>{booking.roomName}</p><p className="text-slate-500"><span className="block text-xs text-slate-400">KHÁCH</span>{booking.adults} NL{booking.children ? ` · ${booking.children} TE` : ""}</p><p className="col-span-2 text-slate-600"><span className="block text-xs text-slate-400">LƯU TRÚ</span>{dateLabel(booking.checkIn)} — {dateLabel(booking.checkOut)}</p></div>{booking.note && <p className="text-xs text-slate-400 italic mt-3">“{booking.note}”</p>}<div className="mt-4"><Actions booking={booking} /></div></article>)}</div>}
  </div>;
}
